package:
  name: pypardiso
  version: "0.3.1"

source:
  git_rev: origin/master
  git_url: https://github.com/haasad/PyPardisoProject.git

build:
  noarch: python
  script: "python setup.py install --single-version-externally-managed --record record.txt"

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - mkl
    - numpy
    - scipy
    - mkl-service
    - psutil

about:
  home: https://github.com/haasad/PyPardisoProject
  license: BSD
  license_file: LICENSE.txt
  summary: Python interface to the Intel MKL Pardiso library to solve large sparse linear systems of equations
