name: pypardiso-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Run the tests once every 24 hours to catch dependency problems early
    - cron: '0 7 * * *'

jobs:
  pip-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --user -r requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          python -m pytest
